import type { LucideProps } from "lucide-react";
import {
  ArrowLeft,
  ArrowUpRight,
  BadgePercent,
  Bell,
  Bot,
  Camera,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  Globe,
  Heart,
  Headphones,
  Home,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Lock,
  LogOut,
  Menu,
  MessageSquareMore,
  MessageCircle,
  MapPin,
  Package,
  PackageOpen,
  PieChart,
  Ruler,
  Search,
  Settings2,
  Shield,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Store,
  SunMedium,
  Truck,
  UserRound,
  Users,
  Wallet,
  X,
  MoonStar,
} from "lucide-react";

const iconMap = {
  home: Home,
  categories: LayoutGrid,
  offers: BadgePercent,
  cart: ShoppingBag,
  profile: UserRound,
  landing: Sparkles,
  settings: Settings2,
  admin: Shield,
  search: Search,
  menu: Menu,
  close: X,
  globe: Globe,
  sun: SunMedium,
  moon: MoonStar,
  shirt: Shirt,
  chart: LineChart,
  bell: Bell,
  external: ArrowUpRight,
  logout: LogOut,
  revenue: CircleDollarSign,
  packageOpen: PackageOpen,
  truck: Truck,
  dashboard: LayoutDashboard,
  users: Users,
  pieChart: PieChart,
  sliders: SlidersHorizontal,
  bot: Bot,
  pos: Wallet,
  lock: Lock,
  wallet: Wallet,
  whatsapp: MessageCircle,
  support: MessageSquareMore,
  sizeGuide: Ruler,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  instagram: Camera,
  facebook: Globe,
  heart: Heart,
  store: Store,
  back: ArrowLeft,
  payment: CreditCard,
  mapPin: MapPin,
  headphones: Headphones,
  package: Package,
} as const;

export type AppIconName = keyof typeof iconMap;

type Props = LucideProps & {
  name: AppIconName;
};

export default function AppIcon({ name, ...props }: Props) {
  const Icon = iconMap[name];
  return <Icon aria-hidden="true" {...props} />;
}
